services:

  db:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    container_name: django-app-alchemy
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - PORT=8000
    restart: always
    depends_on:
      - db

volumes:
  postgres_data: