services:

  db:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379

  app:
    container_name: django-app-alchemy
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    env_file:
      - ./.env
    environment:
      - PORT=8000
    restart: always
    depends_on:
      - db
      - redis

  celery:
    container_name: celery-worker-alchemy
    build:
      context: .
    command: celery -A project_alchemy worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
  
  celery-beat:
    container_name: celery-beat-alchemy
    build:
      context: .
    command: celery -A project_alchemy beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: