# Generated by Django 5.1.2 on 2024-11-29 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_publication_date_document_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='unstructured_data',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
