# Generated by Django 5.1.2 on 2024-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tasklog_delete_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='log_messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
