# Generated by Django 5.1.2 on 2024-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_qapair'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cleaned_data',
            field=models.TextField(null=True),
        ),
    ]
