# Generated by Django 5.1.2 on 2024-12-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_document_cleaned_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qapair',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=10),
        ),
    ]
