# Generated by Django 5.1.2 on 2024-12-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_qapair_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qapair',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
