# Generated by Django 5.1.2 on 2024-12-18 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_qapair_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='core.document'),
        ),
    ]
